"""
SETUP: set openai.api_key_path to the path to the file which contains the api key
"""
import os
import openai

openai.api_key_path = "/Users/samzorpette/Desktop/memory lane/SECRET_KEY/openai.txt"

def summarize(text):
    response = openai.Completion.create(
    model="text-davinci-003",
    prompt="Summarize this story and ask a follow up question about it: \n\n" + text,
    temperature=0.7,
    max_tokens=150,
    top_p=1.0,
    frequency_penalty=0.0,
    presence_penalty=0.0
    )
    #print("SUMMARY: ")
    #print(response)
    response_text = response.choices[0].text
    response_seperated = response_text.split('Follow up question:')
    return(response_text, response_seperated)

red_riding_hood = 'Once upon a time there was a dear little girl who was loved by every one who looked at her, but most of all by her grandmother, and there was nothing that she would not have given to the child. Once she gave her a little cap of red velvet, which suited her so well that she would never wear anything else. So she was always called Little Red Riding Hood. One day her mother said to her, "Come, Little Red Riding Hood, here is a piece of cake and a bottle of wine. Take them to your grandmother, she is ill and weak, and they will do her good. Set out before it gets hot, and when you are going, walk nicely and quietly and do not run off the path, or you may fall and break the bottle, and then your grandmother will get nothing. And when you go into her room, dont forget to say, good-morning, and dont peep into every corner before you do it." I will take great care, said Little Red Riding Hood to her mother, and gave her hand on it. The grandmother lived out in the wood, half a league from the village, and just as Little Red Riding Hood entered the wood, a wolf met her. Little Red Riding Hood did not know what a wicked creature he was, and was not at all afraid of him. "Good-day, Little Red Riding Hood," said he. "Thank you kindly, wolf." "Whither away so early, Little Red Riding Hood?" "To my grandmothers." "What have you got in your apron?""Cake and wine. Yesterday was baking-day, so poor sick grandmother is to have something good, to make her stronger." "Where does your grandmother live, Little Red Riding Hood?" "A good quarter of a league farther on in the wood. Her house stands under the three large oak-trees, the nut-trees are just below. You surely must know it," replied Little Red Riding Hood.The wolf thought to himself, "What a tender young creature. What a nice plump mouthful, she will be better to eat than the old woman. I must act craftily, so as to catch both." So he walked for a short time by the side of Little Red Riding Hood, and then he said, "see Little Red Riding Hood, how pretty the flowers are about here. Why do you not look round. I believe, too, that you do not hear how sweetly the little birds are singing. You walk gravely along as if you were going to school, while everything else out here in the wood is merry."Little Red Riding Hood raised her eyes, and when she saw the sunbeams dancing here and there through the trees, and pretty flowers growing everywhere, she thought, suppose I take grandmother a fresh nosegay. That would please her too. It is so early in the day that I shall still get there in good time. And so she ran from the path into the wood to look for flowers. And whenever she had picked one, she fancied that she saw a still prettier one farther on, and ran after it, and so got deeper and deeper into the wood.'
bonnie_runnels_transcript = "My name is Regent Nur, I am 16 years old. Today is November 25th and I'm speaking with Bonnie Reynolds, who is my Grandma, we're recording this interview in Arkansas. Can you tell me about one or two people who have been the biggest influences on your life? Well, probably my parents cuz they worked so hard and We're poor but but we never felt for anything. We didn't know we were poor. So they had a big influence and probably my family. Very impressed by my family. They're all hard workers. Can you tell me about the dumbest thing you ever did in your life? If you would like to answer that? I did not go to college right after high school and that was the dumbest thing I've ever done. So later after I married, I took College courses. Wherever we lived took classes at Indiana University. In Sacramento, State and University of Arkansas, and probably a couple more places but I wish I had gone right after high school. I feel like I missed a college last that way. What jobs did you have? When you were a teenager, how are your first job, probably working in a little grocery store on the corner of our street, cleaning shelves. And Stalking things and waiting on customers. Can you tell me about some of the most important lessons you've learned in life or 10, most important lessons to treat people kindly, and to respect everyone's opinion. So you don't have to agree with people, but you have to be civil and Agree to disagree and not be hateful about your disagreements. I agree with you. Your husband, Brian. We met on a summer vacation. In South Bend, Indiana. I went back to visit my cousins, who I, I grew up in South Bend, but we moved to California when I was 12. So, I went back for vacation and he was dating my cousin on and off when he was home from Purdue and I met him and we decided to date instead of and he got My cousin a date from double dated, and it's all history after that. What are you most grateful for my family? The love of my family. I couldn't be happier. Couldn't have picked better people and I'm just so fortunate for that and that we live, where we live. All right. Last one. What advice would you give to your teenage self? If you could go back and do it over again? Don't worry about what other people think of you and be a leader, not a follower. Thank you, Grandma. You're welcome. Thank you for interview."

summarize(bonnie_runnels_transcript)
